### ISSUE TITLE
command 'px-to-viewport.convertPxToRem' not found

### ISSUE THREAD

**Issue by intherightdirection** [Rohit-B-Kadam/vscode-px-to-viewport-extension#1]
When I try to use key bindings I get a VS Code popup: command 'px-to-viewport.convertPxToRem' not found

Windows 10 Pro :  Build 10.0.19043 Build 19043
VS Code: V1.63.2

**Comment by Rohit-B-Kadam** [comment]
Hi Jared Dunlop,
Thank you for identifying this issue. I am also getting the same error. Will try to solve this problem till then you can use this extension using Command Palette. 
Press (Ctrl+Shift+P) to open Command Palette then type convert px to rem. 

In my observation after using the command palette then key bindings were working. Strange

**Comment by Naozumi520** [comment]
I'm also getting the same error and currently all method are not working.

**Comment by Rohit-B-Kadam** [comment]
It is an activation problem. The extension is not activated by vscode.

To manually activate the extension:
Press (Ctrl+Shift+P) to open Command Palette, then type convert px to vw.
