### ISSUE TITLE
 command 'px-to-viewport.convertPxToVh' not found

### ISSUE THREAD

**Issue by YashasaveeKesarwani99** [Rohit-B-Kadam/vscode-px-to-viewport-extension#2]
while trying to convert px to vh, this error occurs

**Comment by Rohit-B-Kadam** [comment]
Thank you for your feedback.
Currently, I am busy with other work. But I will try to take some time out of my schedule to fix this issue.

 Till then you can use the extension using Command Palette.
 Press (Ctrl+Shift+P) to open Command Palette then type convert px to vh.

**Comment by Rohit-B-Kadam** [comment]
Hi @YashasaveeKesarwani99 ,
It is an activation problem. The extension is not activated by vscode.
 
To manually activate the extension:
Press (Ctrl+Shift+P) to open Command Palette, then type convert px to vw.

**Comment by Rohit-B-Kadam** [comment]
Please let me know if the above solution works for you.

Thanks for using this extension.

**Comment by Rohit-B-Kadam** [comment]
Closing this issue due to inactive
