### ISSUE TITLE
Didn't work at all for me.

### ISSUE THREAD

**Issue by HeatherHerries** [Rohit-B-Kadam/vscode-px-to-viewport-extension#3]
This didn't at all for me. Had high hopes since i do this regularly. I'm working on a Mac maybe I'm doing something wrong. Great idea in theory.

**Comment by Rohit-B-Kadam** [comment]
Do you see any errors? If yes can you mention it here

**Comment by Rohit-B-Kadam** [comment]
It can be an activation problem. Sometimes the extension is not activated by vscode.

To manually activate the extension:
Press (Ctrl+Shift+P) to open Command Palette, then type convert px to vw.

If the shortcuts don't work you can use this feature through the command palette. 
Steps:
1. Select the value you want to convert.
2. Ctrl+Shift+P to open the command palette
3. Type convert you will see all the options available for conversion.

**Comment by Rohit-B-Kadam** [comment]
As I have answered your question, I am closing this issue.
